org: sachack
app: bridge
service: gap

plugins:
  - serverless-esbuild
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing
  - serverless-dynamodb-local
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: 'node14'  # Set according to your runtime
    loader: 
      '.html': 'text'  # Treat HTML files as raw text

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  region: us-west-1
  stage: dev
  deploymentMethod: direct
  tracing:
    lambda: true
    apiGateway: true
  environment:
    GEMINI_KEY: ${param:GEMINI_KEY}
    GEMINI_URL: ${param:GEMINI_URL}
    GOOGLE_API_KEY: ${param:GEMINI_KEY}
    USER_SCHEMA: UserTable

functions:
  signUp:
    handler: src/signUp.handler
    events:
      - http:
          path: /signup
          method: post
          cors: true
          request:
            schemas:
              application/json: ${file(models/signup-model.json)}
    iamRoleStatementsName: userSignUpPostRole
    iamRoleStatements:
      - Effect: Allow
        Action:
          - xray:PutTelemetryRecords
          - xray:PutTraceSegments
        Resource:
          - !GetAtt UserTable.Arn
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_SCHEMA}"
    
  login:
    handler: src/login.handler
    events:
      - http:
          path: /login
          method: post
          cors: true
          request:
            schemas:
              application/json: ${file(models/login-model.json)}
    iamRoleStatementsName: userLoginRole
    iamRoleStatements:
      - Effect: Allow
        Action:
          - xray:PutTelemetryRecords
          - xray:PutTraceSegments
        Resource:
          - !GetAtt UserTable.Arn
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Scan
          - dynamodb:Query
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_SCHEMA}"

  geminiHandler:
    handler: src/geminiLangChain.handler
    events:
      - http:
          path: /gemini/benefits
          method: post
          cors: true
          request:
            schemas:
              application/json: ${file(models/gemini-benefits-model.json)}
    timeout: 30

  geminiParseHandler:
    handler: src/geminiUserData.handler
    events:
      - http:
          path: /gemini/userdata
          method: post
          cors: true
          request:
            schemas:
              application/json: ${file(models/gemini-user-data-model.json)}
    timeout: 30

resources:
  Resources:
    UserTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.USER_SCHEMA}
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        BillingMode: PAY_PER_REQUEST